In [257]:
import numpy as np

def triag (B):
    n = len(B)
    i = 0
    j = 0
    
    while i < n:
            B[i] = B[i]/B[i][i]
            j = i
            while j < n:
                if j == i:
                    j = j+1
                else: 
                    B[j]=B[j]-B[i]*B[j][i]
                    j = j+1
            j = 0
            i = i+1
            y = np.array(B[:,n]).T
            R = np.array(B[:n,:n])
    return R,y,B

In [258]:
A = np.array([[1,1/2],
            [1/2, 1/2]])
lös = np.array([[1/2,1/4]])

#a,b,c=triag(A,lös)
np.concatenate((A,lös.T),axis=1)

array([[1.  , 0.5 , 0.5 ],
       [0.5 , 0.5 , 0.25]])

In [330]:
unitymatrix = None
def unity(A):
    n = len(A)
    i = 0
    j = 0
    while i < n:
        if A[i][i] == 1:
            while j < n:
                if A[i][j] == 0:
                    print('unity matrix')
                    j = j+1
                    i = i+1
                    unitymatrix = True
                    break
                else:
                    print('no unity matrix: need for backward substitution')
                    unitymatrix = False
                    break
            break

In [315]:
def backward(C):
    n = len(C)
    m = len(C)-1
    x = np.ones(n)
    R = np.array(C[:n,:n])
    y = np.array(C[:,n])
    for i in range(m,-1,-1):
        x[i] = y[i]
        for j in range(m,i+1,-1):
            x[i] = x[i] - C[i][j]*x[j]
    return x

In [261]:
#Funktion für a,b,c,y in matrix patschen
def matrix(a,b,c,y):
    n = len(b)
    matrix = np.array(np.ones(n)*0)
    i = 1
    mat = matrix
    while i < n:
        mat = np.vstack((mat,matrix))
        i = i+1
    j = 0
    while j < n:
        mat[j][j] = b[j]
        j = j+1
    k = 0
    while k < n-1:
        mat[k+1][k] = a[k]
        k = k+1
    p = 0
    while p < n-1:
        mat[p][p+1] = c[p]
        p = p+1
    mat = np.hstack((mat,y))
    return mat


In [ ]:
#erst Daten eingeben und Matrix erstellen
#dann Dreiecksmatrix machen mit Gauß
#checken ob Einheitsmatrix:
    #-> ja: Ausgabe von x
    #-> nein: backsub
            #dann Ausgabe von x

In [352]:
def solution(a,b,c,y):
    mat = matrix(a,b,c,y)
    R,y,B = triag(mat)
    unity(R)
    print('the solution is:')
    if unitymatrix == True:
        print(y)
    else:
        x = backward(B)
    return x
        

In [328]:
a = np.array([1,2])
b = np.array([5,9,10])
c = np.array([-6,1])
y = np.array([[4],[1],[3]])

In [353]:
solution(a,b,c,y)

no unity matrix: need for backward substitution
the solution is:


array([0.06666667, 0.1       , 0.11428571, 0.12      , 0.12222222,
       0.12307692, 0.12340426, 0.12352941, 0.12357724, 0.12359551])

In [354]:
#nr 4
N = 10
a = np.ones(N-1)*(-1)
b = np.ones(N)*3
c = np.ones(N-1)*(-1)
y = np.array([[0.2],[0.2],[0.2],[0.2],[0.2],[0.2],[0.2],[0.2],[0.2],[0.2]])

solution(a,b,c,y)


no unity matrix: need for backward substitution
the solution is:


array([0.06666667, 0.1       , 0.11428571, 0.12      , 0.12222222,
       0.12307692, 0.12340426, 0.12352941, 0.12357724, 0.12359551])

In [355]:
xx = solution(a,b,c,y)

no unity matrix: need for backward substitution
the solution is:


In [356]:
def matrix_ohne_lös(a,b,c):
    n = len(b)
    matrix = np.array(np.ones(n)*0)
    i = 1
    mat = matrix
    while i < n:
        mat = np.vstack((mat,matrix))
        i = i+1
    j = 0
    while j < n:
        mat[j][j] = b[j]
        j = j+1
    k = 0
    while k < n-1:
        mat[k+1][k] = a[k]
        k = k+1
    p = 0
    while p < n-1:
        mat[p][p+1] = c[p]
        p = p+1
    return mat

In [358]:
matrix = matrix_ohne_lös(a,b,c)

In [360]:
np.dot(matrix,xx)

array([0.1       , 0.11904762, 0.12285714, 0.12349206, 0.12358974,
       0.12360429, 0.12360643, 0.12360674, 0.12360679, 0.24720928])