In [2]:
import numpy as np

In [19]:
A = np.array([[-1, 0, 0, -20, -30, -5],
              [0, -1, 0, -1, -3, -7],
              [0, 0, -1, -4, -10, -20],
              [20, 30, 35, 0, 0, 0],
              [3 ,3 ,3, 0, 0, 0],
              [7, 8, 20, 0, 0, 0]])

In [20]:
print(A)

[[ -1   0   0 -20 -30  -5]
 [  0  -1   0  -1  -3  -7]
 [  0   0  -1  -4 -10 -20]
 [ 20  30  35   0   0   0]
 [  3   3   3   0   0   0]
 [  7   8  20   0   0   0]]


In [21]:
ev,vecs = np.linalg.eig(A)

In [22]:
ev, vecs

(array([-0.5       +33.62558388j, -0.5       -33.62558388j,
        -0.5        +7.67949446j, -0.5        -7.67949446j,
        -1.13602378 +0.j        ,  0.13602378 +0.j        ]),
 array([[-0.00808048+5.43421815e-01j, -0.00808048-5.43421815e-01j,
         -0.86913661+0.00000000e+00j, -0.86913661-0.00000000e+00j,
         -0.53762066+0.00000000e+00j,  0.08149945+0.00000000e+00j],
        [-0.00138394+9.30713447e-02j, -0.00138394-9.30713447e-02j,
          0.13809399-1.49619900e-16j,  0.13809399+1.49619900e-16j,
          0.29472269+0.00000000e+00j, -0.04467786+0.00000000e+00j],
        [-0.00436622+2.93633078e-01j, -0.00436622-2.93633078e-01j,
          0.34158855+2.77555756e-17j,  0.34158855-2.77555756e-17j,
          0.07549029+0.00000000e+00j, -0.01144379+0.00000000e+00j],
        [ 0.71189052+0.00000000e+00j,  0.71189052-0.00000000e+00j,
          0.01084273+1.66533346e-01j,  0.01084273-1.66533346e-01j,
         -0.64384894+0.00000000e+00j, -0.81514582+0.00000000e+00j],
        [ 

In [42]:
len(vecs)

6

In [52]:
ev,vecs = np.linalg.eig(A)
n = 3*vecs[0]+3*vecs[1]+vecs[2]+vecs[3]+5*vecs[4]+0.1*vecs[5]
print(n)

[ 1.12504188+2.20311256j  1.12504188-2.20311256j -1.7929415 +0.9000031j
 -1.7929415 -0.9000031j   0.90421379+0.j          2.07079142+0.j        ]
